name: Linux Runner with SSH Access

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  connect:
    runs-on: ubuntu-latest  # Use your self-hosted runner (make sure the labels match)
    timeout-minutes: 9999  # Keep the job running for a long time (adjust as needed)
    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: lstocchi